apiVersion: apps/v1
kind: Deployment
metadata:
  name: passwords-prod
  labels:
    app: passwords-prod
spec:
  selector:
    matchLabels:
      app: passwords-prod
  template:
    metadata:
      labels:
        app: passwords-prod
    spec:

      containers:
        - name: passwords-prod
          image: '${CI_REGISTRY}/${CI_PROJECT_PATH}:${BRANCH_SLUG_SHORT}-${CI_COMMIT_SHORT_SHA}'
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: passwords-env
      imagePullSecrets:
        - name: 'docker-registry'
  revisionHistoryLimit: 1
---
kind: Service
apiVersion: v1
metadata:
  name: passwords-prod
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: passwords-prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: passwords-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - api.passwords.interaapps.de
      secretName: passwords-prod-ssl
  rules:
    - host: api.passwords.interaapps.de
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: passwords-prod
                port:
                  number: 80